let input = document.getElementById("input");
let tombol = document.getElementById("tombol");
let hasil = document.getElementById("hasil");
let nama = document.getElementById("nama");

tombol.addEventListener("click", cekKhodam);

function cekKhodam() {
  nama.innerHTML = input.value;
  let angkaRandom = Math.floor(Math.random() * namaKhodam.length);
  hasil.innerHTML = `${namaKhodam[angkaRandom]}`;
}

const namaKhodam = [
 "Ayam Terbang",
 "Kuda Awan",
 "Singa Berkepala Dua",
 "Gajah Terbang",
 "Kucing Laba-laba",
 "Ikan Pelompat",
 "Kelelawar Raksasa",
 "Burung Baja",
 "Naga Laut",
 "Penguin Terbang",
 "Kuda Laut Terbang",
 "Gajah Terbang Bebek",
 "Ikan Pembalik Dunia",
 "Cacing Terbang",
 "Kucing Raksasa",
 "Kura-kura Terbang",
 "Pinguin Berapi",
 "Singa Kecil",
 "Naga Jambul",
 "Serigala Laut",
 "Gajah Bersayap",
 "Ayam Tanpa Kepala",
 "Kupu-kupu Hitam",
 "Kelinci Raksasa",
 "Harimau Awan",
 "Ikan Gorila",
 "Lumba-lumba Api",
 "Babi Terbang",
 "Elang Jantan",
 "Tikus Raksasa",
 "Cheetah Terbang",
 "Kuda Jari Besi",
 "Anjing Api",
 "Kelelawar Laut",
 "Burung Krokodil",
 "Ular Terbang",
 "Kodok Berkepala Dua",
 "Zebra Terkutuk",
 "Serigala Terbang",
 "Buaya Berbulu",
 "Ikan Menggigit Awan",
 "Monyet Jauh",
 "Kuda Raksasa",
 "Ayam Api",
 "Ular Bakar",
 "Ikan Dunia Terbalik",
 "Kucing Laut",
 "Monyet Batu",
 "Singa Besi",
 "Kuda Laut Berapi",
 "Kupu-kupu Pemburu",
 "Kodek Api",
 "Gajah Menggigit",
 "Kelinci Pemburu",
 "Harimau Salju",
 "Kelelawar Pemburu",
 "Ikan Terbang Putih",
 "Kura-kura Baja",
 "Burung Cahaya",
 "Singa Laut",
 "Cheetah Pemberani",
 "Harimau Api",
 "Burung Hitam",
 "Ikan Pemburu Laut",
 "Monyet Terbang",
 "Mantis Hitam",
 "Serigala Salju",
 "Monyet Terbang",
 "Gajah Bersayap",
 "Anjing Pemburu Terbang",
 "Kura-kura Bersayap",
 "Burung Pemburu Salju",
 "Harimau Berbulu",
 "Kuda Berapi",
 "Burung Beracun",
 "Singa Terbang",
 "Kupu-kupu Api",
 "Ikan Pembalap",
 "Burung Hitam Bersayap",
 "Monyet Api",
 "Ular Laut Terbang",
 "Jerapah Raksasa",
 "Elang Pemburu",
 "Tikus Terbang",
 "Singa Api",
 "Ikan Perak Terbang",
 "Babi Pemburu",
 "Kuda Hitam",
 "Penguin Api",
 "Kupu-kupu Salju",
 "Serigala Api",
 "Harimau Terbang",
 "Kuda Laut Raksasa",
 "Ikan Laut Berkepala Dua",
 "Kucing Hitam",
 "Gajah Pemburu",
 "Elang Pemburu Terbang",
 "Babi Laut",
 "Burung Pemburu",
 "Singa Raksasa",
 "Anjing Laut",
 "Singa Laba-laba",
 "Penguin Laut",
 "Babi Raksasa",
 "Ular Hitam",
 "Burung Laut Pemburu"
];
